// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvqvzksspkiskmuunuyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2cXZ6a3NzcGtpc2ttdXVudXl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1Nzk1NzYsImV4cCI6MjA3MDE1NTU3Nn0.US17D8kuAkp3gZPq_OuJeSe8ybUKBF6IZgEzekvISjI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});